object Host "alertmanager" {
  check_command = "dummy"
  enable_passive_checks = false
  enable_perfdata = false
}

object Service "alertmanager-heartbeat" {
  check_command = "dummy"
  check_interval = 10s

  host_name = "alertmanager"

  vars.dummy_state = 2
  vars.dummy_text = {{
    var service = get_service(macro("$host.name$"), macro("$service.name$"))
    var lastCheck = DateTime(service.last_check).to_string()
    return "No check results received. Last result time: " + lastCheck
  }}
}

object ApiUser "alertmanager"  {
  password = "CHANGEME"
  permissions = [
    {
      permission = "objects/query/*"
      filter = {{ host.name == "alertmanager" }}
    },
    {
      permission = "objects/create/service"
      filter = {{ host.name == "alertmanager" }}
    },
    {
      permission = "objects/modify/service"
      filter = {{ host.name == "alertmanager" }}
    },
    {
      permission = "objects/delete/service"
      filter = {{ host.name == "alertmanager" }}
    },
    {
      permission = "actions/process-check-result"
      filter = {{ host.name == "alertmanager" }}
    },
  ]
}
